- pandas ile veri yükleme
- verileri keşfetme (`.mean()`, `.value_counts()`)
- verileri maskelerle filtreleme
- eksik değerlerin işlenmesi (`.dropna()`, `.fillna()`)
- verilere fonksiyon uygulama (`.apply()` and `.map()`)
- verileri gruplama ve toplama

### Loading Data - Veri seti yükleme



Tahıllarla ilgili dataset: [Kaggle](https://www.kaggle.com/crawford/80-cereals) ve orjinal dataset : [dataset](https://perso.telecom-paristech.fr/eagan/class/igr204/datasets).

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://bit.ly/2JRmGC2')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 16 columns):
name        77 non-null object
mfr         77 non-null object
type        77 non-null object
calories    77 non-null int64
protein     77 non-null int64
fat         77 non-null int64
sodium      77 non-null int64
fiber       77 non-null float64
carbo       77 non-null float64
sugars      77 non-null int64
potass      77 non-null int64
vitamins    77 non-null int64
shelf       77 non-null int64
weight      77 non-null float64
cups        77 non-null float64
rating      77 non-null float64
dtypes: float64(5), int64(8), object(3)
memory usage: 9.8+ KB

In [4]:
df.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843

`.info()`'dan bu veri kümesinde boş değerlerimiz yok gibi görünüyor. Ama Almond Delight için son sıraya bakın. Bu veri kümesinin yazarları, eksik değerleri belirtmek için -1 kullanmış gibi görünüyor. Bunu şimdi dönüştürebiliriz veya bize yardımcı olması için `.read_csv()` argümanlarını kullanabiliriz. Ayrıca tahıl adını veri çerçevemizin indeksi olacak şekilde ayarlayalım.

In [5]:
df = pd.read_csv('https://bit.ly/2JRmGC2', 
                 na_values = -1,     # -1 değerlerini NaN değerlere dönüştürme
                 index_col = 0
                )

In [6]:
df.head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.0,0.75,34.384843

`.read_csv()` verilerinizi pandas ile yüklerken doğru şekilde biçimlendirmemize yardımcı olacak bir sürü yerleşik parametreye sahiptir.

- `sep` ile verilerin  nasıl ayrılacağını ayarlarız (örneğin; ',' veya '\t' gibi)
- `nrows` ile verilerimizin yalnızca bir kısmını yükleyebiliriz
- `thousands` ile 2.000 gibi sayıları binli tam sayılara çeviririz

Herhangi bir nesne veya işlev için mevcut tüm seçenekleri görmek için soru işaretini kullanırız

In [7]:
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: Union[str, pathlib.Path, IO[~AnyStr]],
    sep=',',
    delimiter=None,
    header='infer',
    names=None,
    index_col=None,
    usecols=None,
    squeeze=False,
    prefix=None,
    mangle_dupe_cols=True,
    dtype=None,
    engine=None,
    converters=None,
    true_values=None,
    false_values=None,
    skipinitialspace=False,
    skiprows=None,
    skipfooter=0,
    nrows=None,
    na_values=None,
    keep_default_na=True,
    na_filter=True,
    verbose=False,
    skip_blank_lines=True,
    parse_dates=False,
    infer_datetime_format=False,
    keep_date_col=False,
    date_parser=None,
    dayfirst=False,
    cache_dates=True,
    iterator=False,
    chunksize=None,
    compression='infer',
    thousands=None,
    decimal=b'.',
    lineterminator=None,
    quotechar='"',
    quoting=0,
    doublequote=True,
    escapechar=None,
    comment=None,
    encoding=None,
    dialect=None,
    error_bad_lines=True,
    warn_bad_lines=True,
    delim_whitespace=False,
    low_memory=True,
    memory_map=False,
    float_precision=None,
)
Docstring:
Read a comma-separated values (csv) file into DataFrame.

Also supports optionally iterating or breaking of the file
into chunks.

Additional help can be found in the online docs for
`IO Tools <http://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

Parameters
----------
filepath_or_buffer : str, path object or file-like object
    Any valid string path is acceptable. The string could be a URL. Valid
    URL schemes include http, ftp, s3, and file. For file URLs, a host is
    expected. A local file could be: file://localhost/path/to/table.csv.

    If you want to pass in a path object, pandas accepts any ``os.PathLike``.

    By file-like object, we refer to objects with a ``read()`` method, such as
    a file handler (e.g. via builtin ``open`` function) or ``StringIO``.
sep : str, default ','
    Delimiter to use. If sep is None, the C engine cannot automatically detect
    the separator, but the Python parsing engine can, meaning the latter will
    be used and automatically detect the separator by Python's builtin sniffer
    tool, ``csv.Sniffer``. In addition, separators longer than 1 character and
    different from ``'\s+'`` will be interpreted as regular expressions and
    will also force the use of the Python parsing engine. Note that regex
    delimiters are prone to ignoring quoted data. Regex example: ``'\r\t'``.
delimiter : str, default ``None``
    Alias for sep.
header : int, list of int, default 'infer'
    Row number(s) to use as the column names, and the start of the
    data.  Default behavior is to infer the column names: if no names
    are passed the behavior is identical to ``header=0`` and column
    names are inferred from the first line of the file, if column
    names are passed explicitly then the behavior is identical to
    ``header=None``. Explicitly pass ``header=0`` to be able to
    replace existing names. The header can be a list of integers that
    specify row locations for a multi-index on the columns
    e.g. [0,1,3]. Intervening rows that are not specified will be
    skipped (e.g. 2 in this example is skipped). Note that this
    parameter ignores commented lines and empty lines if
    ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
    data rather than the first line of the file.
names : array-like, optional
    List of column names to use. If file contains no header row, then you
    should explicitly pass ``header=None``. Duplicates in this list are not
    allowed.
index_col : int, str, sequence of int / str, or False, default ``None``
  Column(s) to use as the row labels of the ``DataFrame``, either given as
  string name or column index. If a sequence of int / str is given, a
  MultiIndex is used.

  Note: ``index_col=False`` can be used to force pandas to *not* use the first
  column as the index, e.g. when you have a malformed file with delimiters at
  the end of each line.
usecols : list-like or callable, optional
    Return a subset of the columns. If list-like, all elements must either
    be positional (i.e. integer indices into the document columns) or strings
    that correspond to column names provided either by the user in `names` or
    inferred from the document header row(s). For example, a valid list-like
    `usecols` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
    Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
    To instantiate a DataFrame from ``data`` with element order preserved use
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]`` for columns
    in ``['foo', 'bar']`` order or
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
    for ``['bar', 'foo']`` order.

    If callable, the callable function will be evaluated against the column
    names, returning names where the callable function evaluates to True. An
    example of a valid callable argument would be ``lambda x: x.upper() in
    ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
    parsing time and lower memory usage.
squeeze : bool, default False
    If the parsed data only contains one column then return a Series.
prefix : str, optional
    Prefix to add to column numbers when no header, e.g. 'X' for X0, X1, ...
mangle_dupe_cols : bool, default True
    Duplicate columns will be specified as 'X', 'X.1', ...'X.N', rather than
    'X'...'X'. Passing in False will cause data to be overwritten if there
    are duplicate names in the columns.
dtype : Type name or dict of column -> type, optional
    Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32,
    'c': 'Int64'}
    Use `str` or `object` together with suitable `na_values` settings
    to preserve and not interpret dtype.
    If converters are specified, they will be applied INSTEAD
    of dtype conversion.
engine : {'c', 'python'}, optional
    Parser engine to use. The C engine is faster while the python engine is
    currently more feature-complete.
converters : dict, optional
    Dict of functions for converting values in certain columns. Keys can either
    be integers or column labels.
true_values : list, optional
    Values to consider as True.
false_values : list, optional
    Values to consider as False.
skipinitialspace : bool, default False
    Skip spaces after delimiter.
skiprows : list-like, int or callable, optional
    Line numbers to skip (0-indexed) or number of lines to skip (int)
    at the start of the file.

    If callable, the callable function will be evaluated against the row
    indices, returning True if the row should be skipped and False otherwise.
    An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
skipfooter : int, default 0
    Number of lines at bottom of file to skip (Unsupported with engine='c').
nrows : int, optional
    Number of rows of file to read. Useful for reading pieces of large files.
na_values : scalar, str, list-like, or dict, optional
    Additional strings to recognize as NA/NaN. If dict passed, specific
    per-column NA values.  By default the following values are interpreted as
    NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
    '1.#IND', '1.#QNAN', 'N/A', 'NA', 'NULL', 'NaN', 'n/a', 'nan',
    'null'.
keep_default_na : bool, default True
    Whether or not to include the default NaN values when parsing the data.
    Depending on whether `na_values` is passed in, the behavior is as follows:

    * If `keep_default_na` is True, and `na_values` are specified, `na_values`
      is appended to the default NaN values used for parsing.
    * If `keep_default_na` is True, and `na_values` are not specified, only
      the default NaN values are used for parsing.
    * If `keep_default_na` is False, and `na_values` are specified, only
      the NaN values specified `na_values` are used for parsing.
    * If `keep_default_na` is False, and `na_values` are not specified, no
      strings will be parsed as NaN.

    Note that if `na_filter` is passed in as False, the `keep_default_na` and
    `na_values` parameters will be ignored.
na_filter : bool, default True
    Detect missing value markers (empty strings and the value of na_values). In
    data without any NAs, passing na_filter=False can improve the performance
    of reading a large file.
verbose : bool, default False
    Indicate number of NA values placed in non-numeric columns.
skip_blank_lines : bool, default True
    If True, skip over blank lines rather than interpreting as NaN values.
parse_dates : bool or list of int or names or list of lists or dict, default False
    The behavior is as follows:

    * boolean. If True -> try parsing the index.
    * list of int or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
      each as a separate date column.
    * list of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
      a single date column.
    * dict, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call
      result 'foo'

    If a column or index cannot be represented as an array of datetimes,
    say because of an unparseable value or a mixture of timezones, the column
    or index will be returned unaltered as an object data type. For
    non-standard datetime parsing, use ``pd.to_datetime`` after
    ``pd.read_csv``. To parse an index or column with a mixture of timezones,
    specify ``date_parser`` to be a partially-applied
    :func:`pandas.to_datetime` with ``utc=True``. See
    :ref:`io.csv.mixed_timezones` for more.

    Note: A fast-path exists for iso8601-formatted dates.
infer_datetime_format : bool, default False
    If True and `parse_dates` is enabled, pandas will attempt to infer the
    format of the datetime strings in the columns, and if it can be inferred,
    switch to a faster method of parsing them. In some cases this can increase
    the parsing speed by 5-10x.
keep_date_col : bool, default False
    If True and `parse_dates` specifies combining multiple columns then
    keep the original columns.
date_parser : function, optional
    Function to use for converting a sequence of string columns to an array of
    datetime instances. The default uses ``dateutil.parser.parser`` to do the
    conversion. Pandas will try to call `date_parser` in three different ways,
    advancing to the next if an exception occurs: 1) Pass one or more arrays
    (as defined by `parse_dates`) as arguments; 2) concatenate (row-wise) the
    string values from the columns defined by `parse_dates` into a single array
    and pass that; and 3) call `date_parser` once for each row using one or
    more strings (corresponding to the columns defined by `parse_dates`) as
    arguments.
dayfirst : bool, default False
    DD/MM format dates, international and European format.
cache_dates : boolean, default True
    If True, use a cache of unique, converted dates to apply the datetime
    conversion. May produce significant speed-up when parsing duplicate
    date strings, especially ones with timezone offsets.

    .. versionadded:: 0.25.0
iterator : bool, default False
    Return TextFileReader object for iteration or getting chunks with
    ``get_chunk()``.
chunksize : int, optional
    Return TextFileReader object for iteration.
    See the `IO Tools docs
    <http://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
    for more information on ``iterator`` and ``chunksize``.
compression : {'infer', 'gzip', 'bz2', 'zip', 'xz', None}, default 'infer'
    For on-the-fly decompression of on-disk data. If 'infer' and
    `filepath_or_buffer` is path-like, then detect compression from the
    following extensions: '.gz', '.bz2', '.zip', or '.xz' (otherwise no
    decompression). If using 'zip', the ZIP file must contain only one data
    file to be read in. Set to None for no decompression.

    .. versionadded:: 0.18.1 support for 'zip' and 'xz' compression.

thousands : str, optional
    Thousands separator.
decimal : str, default '.'
    Character to recognize as decimal point (e.g. use ',' for European data).
lineterminator : str (length 1), optional
    Character to break file into lines. Only valid with C parser.
quotechar : str (length 1), optional
    The character used to denote the start and end of a quoted item. Quoted
    items can include the delimiter and it will be ignored.
quoting : int or csv.QUOTE_* instance, default 0
    Control field quoting behavior per ``csv.QUOTE_*`` constants. Use one of
    QUOTE_MINIMAL (0), QUOTE_ALL (1), QUOTE_NONNUMERIC (2) or QUOTE_NONE (3).
doublequote : bool, default ``True``
   When quotechar is specified and quoting is not ``QUOTE_NONE``, indicate
   whether or not to interpret two consecutive quotechar elements INSIDE a
   field as a single ``quotechar`` element.
escapechar : str (length 1), optional
    One-character string used to escape other characters.
comment : str, optional
    Indicates remainder of line should not be parsed. If found at the beginning
    of a line, the line will be ignored altogether. This parameter must be a
    single character. Like empty lines (as long as ``skip_blank_lines=True``),
    fully commented lines are ignored by the parameter `header` but not by
    `skiprows`. For example, if ``comment='#'``, parsing
    ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in 'a,b,c' being
    treated as the header.
encoding : str, optional
    Encoding to use for UTF when reading/writing (ex. 'utf-8'). `List of Python
    standard encodings
    <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .
dialect : str or csv.Dialect, optional
    If provided, this parameter will override values (default or not) for the
    following parameters: `delimiter`, `doublequote`, `escapechar`,
    `skipinitialspace`, `quotechar`, and `quoting`. If it is necessary to
    override values, a ParserWarning will be issued. See csv.Dialect
    documentation for more details.
error_bad_lines : bool, default True
    Lines with too many fields (e.g. a csv line with too many commas) will by
    default cause an exception to be raised, and no DataFrame will be returned.
    If False, then these "bad lines" will dropped from the DataFrame that is
    returned.
warn_bad_lines : bool, default True
    If error_bad_lines is False, and warn_bad_lines is True, a warning for each
    "bad line" will be output.
delim_whitespace : bool, default False
    Specifies whether or not whitespace (e.g. ``' '`` or ``'    '``) will be
    used as the sep. Equivalent to setting ``sep='\s+'``. If this option
    is set to True, nothing should be passed in for the ``delimiter``
    parameter.

    .. versionadded:: 0.18.1 support for the Python parser.

low_memory : bool, default True
    Internally process the file in chunks, resulting in lower memory use
    while parsing, but possibly mixed type inference.  To ensure no mixed
    types either set False, or specify the type with the `dtype` parameter.
    Note that the entire file is read into a single DataFrame regardless,
    use the `chunksize` or `iterator` parameter to return the data in chunks.
    (Only valid with C parser).
memory_map : bool, default False
    If a filepath is provided for `filepath_or_buffer`, map the file object
    directly onto memory and access the data directly from there. Using this
    option can improve performance because there is no longer any I/O overhead.
float_precision : str, optional
    Specifies which converter the C engine should use for floating-point
    values. The options are `None` for the ordinary converter,
    `high` for the high-precision converter, and `round_trip` for the
    round-trip converter.

Returns
-------
DataFrame or TextParser
    A comma-separated values (csv) file is returned as two-dimensional
    data structure with labeled axes.

See Also
--------
to_csv : Write DataFrame to a comma-separated values (csv) file.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_fwf : Read a table of fixed-width formatted lines into DataFrame.

Examples
--------
>>> pd.read_csv('data.csv')  # doctest: +SKIP
File:      /usr/lib/python3/dist-packages/pandas/io/parsers.py
Type:      function

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
df['calories']  #calories column

name
100% Bran                     70
100% Natural Bran            120
All-Bran                      70
All-Bran with Extra Fiber     50
Almond Delight               110
                            ...
Triples                      110
Trix                         110
Wheat Chex                   100
Wheaties                     100
Wheaties Honey Gold          110
Name: calories, Length: 77, dtype: int64

In [10]:
df.calories        # 2 gösterim şekli de doğrudur.

name
100% Bran                     70
100% Natural Bran            120
All-Bran                      70
All-Bran with Extra Fiber     50
Almond Delight               110
                            ...
Triples                      110
Trix                         110
Wheat Chex                   100
Wheaties                     100
Wheaties Honey Gold          110
Name: calories, Length: 77, dtype: int64

In [11]:
df.loc['100% Bran']   # Satırları loc ile alırız

mfr              N
type             C
calories        70
protein          4
fat              1
sodium         130
fiber           10
carbo            5
sugars           6
potass         280
vitamins        25
shelf            3
weight           1
cups          0.33
rating      68.403
Name: 100% Bran, dtype: object

## Exploring Data  - Verileri Keşfetme

`.head()` ve `.info()` ile verilere yüzeysel baktık. Şimdi daha detaylı inceleyelim.

In [12]:
df.calories.describe()

count     77.000000
mean     106.883117
std       19.484119
min       50.000000
25%      100.000000
50%      110.000000
75%      110.000000
max      160.000000
Name: calories, dtype: float64

In [13]:
df.sugars.mean()

7.026315789473684

In [14]:
df.mfr.value_counts()   # hangisinden kaç tane olduğunu sayar. Önemli bir fonksiyon

K    23
G    22
P     9
R     8
Q     8
N     6
A     1
Name: mfr, dtype: int64

`.value_counts()` işleminin sonucu, kategorik değerler içeren bir seridir!

In [15]:
vc = df.mfr.value_counts()
type(vc)

pandas.core.series.Series

In [16]:
vc.loc['K']

23

## Filtering Data

Genellikle verilerin belirli kısımlarını keşfetmek isteriz. Verilerimizi filtrelemek için 'mask' adında değişken oluştururuz.

In [17]:
mask = (df.calories > 100)

mask, koşulun o satırda geçerli olup olmadığını True ve False ile döndüren mantıksal operatördür.

In [18]:
mask

name
100% Bran                    False
100% Natural Bran             True
All-Bran                     False
All-Bran with Extra Fiber    False
Almond Delight                True
                             ...
Triples                       True
Trix                          True
Wheat Chex                   False
Wheaties                     False
Wheaties Honey Gold           True
Name: calories, Length: 77, dtype: bool

When you apply the mask only rows with `True` values are kept.

In [19]:
df[mask].head(10)

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.00,1.00,33.983679
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.00,0.75,34.384843
Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10.0,70.0,25,1,1.00,0.75,29.509541
Apple Jacks,K,C,110,2,0,125,1.0,11.0,14.0,30.0,25,2,1.00,1.00,33.174094
Basic 4,G,C,130,3,2,210,2.0,18.0,8.0,100.0,25,3,1.33,0.75,37.038562
Cap'n'Crunch,Q,C,120,1,2,220,0.0,12.0,12.0,35.0,25,2,1.00,0.75,18.042851
Cheerios,G,C,110,6,2,290,2.0,17.0,1.0,105.0,25,1,1.00,1.25,50.764999
Cinnamon Toast Crunch,G,C,120,1,3,210,0.0,13.0,9.0,45.0,25,2,1.00,0.75,19.823573
Clusters,G,C,110,3,2,140,2.0,13.0,7.0,105.0,25,3,1.00,0.50,40.400208
Cocoa Puffs,G,C,110,1,1,180,0.0,12.0,13.0,55.0,25,2,1.00,1.00,22.736446

In [20]:
df[df.calories > 100].head(10)   # Değişken oluşturmak yerine bu şekilde daha kısa bir şekilde de yazabiliriz.

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.00,1.00,33.983679
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.00,0.75,34.384843
Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10.0,70.0,25,1,1.00,0.75,29.509541
Apple Jacks,K,C,110,2,0,125,1.0,11.0,14.0,30.0,25,2,1.00,1.00,33.174094
Basic 4,G,C,130,3,2,210,2.0,18.0,8.0,100.0,25,3,1.33,0.75,37.038562
Cap'n'Crunch,Q,C,120,1,2,220,0.0,12.0,12.0,35.0,25,2,1.00,0.75,18.042851
Cheerios,G,C,110,6,2,290,2.0,17.0,1.0,105.0,25,1,1.00,1.25,50.764999
Cinnamon Toast Crunch,G,C,120,1,3,210,0.0,13.0,9.0,45.0,25,2,1.00,0.75,19.823573
Clusters,G,C,110,3,2,140,2.0,13.0,7.0,105.0,25,3,1.00,0.50,40.400208
Cocoa Puffs,G,C,110,1,1,180,0.0,12.0,13.0,55.0,25,2,1.00,1.00,22.736446

Birden çok sütunda veya birden çok değerde filtreleme yapmak için mantıksal ifadeler ve  mantıksal operatörler kullanılır

In [21]:
mask = (df.calories > 100) & (df.sugars < 8) & ((df.mfr == 'K') | (df.mfr == 'G'))   # &: ve demek, | veya demek

In [22]:
df[mask]

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
Cheerios,G,C,110,6,2,290,2.0,17.0,1.0,105.0,25,1,1.00,1.25,50.764999
Clusters,G,C,110,3,2,140,2.0,13.0,7.0,105.0,25,3,1.00,0.50,40.400208
Cracklin' Oat Bran,K,C,110,3,3,140,4.0,10.0,7.0,160.0,25,3,1.00,0.50,40.448772
Crispix,K,C,110,2,0,220,1.0,21.0,3.0,30.0,25,3,1.00,1.00,46.895644
Just Right Crunchy Nuggets,K,C,110,2,1,170,1.0,17.0,6.0,60.0,100,3,1.00,1.00,36.523683
Kix,G,C,110,2,1,260,0.0,21.0,3.0,40.0,25,2,1.00,1.50,39.241114
Nutri-Grain Almond-Raisin,K,C,140,3,2,220,3.0,21.0,7.0,130.0,25,3,1.33,0.67,40.692320
Rice Krispies,K,C,110,2,0,290,0.0,22.0,3.0,35.0,25,1,1.00,1.00,40.560159
Special K,K,C,110,6,0,230,1.0,16.0,3.0,55.0,25,1,1.00,1.00,53.131324
Total Corn Flakes,G,C,110,2,1,200,0.0,21.0,3.0,35.0,100,3,1.00,1.00,38.839746
Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,25,3,1.00,0.75,39.106174

## Handling Missings - Eksikleri İşleme

Bu veri setinin tamamında yalnızca dört eksik değer var, ancak bunları nasıl ele alabileceğimizi gözden geçirelim.

In [23]:
df.isna().head()  # Eksik değer var mı diye soruyoruz.

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
100% Natural Bran,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
All-Bran,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
All-Bran with Extra Fiber,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Almond Delight,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

In [24]:
df.isna().sum()            # Eksik değerlerin toplamı   #.sum(axis=1) bu şekilde de gösterebiliriz.

mfr         0
type        0
calories    0
protein     0
fat         0
sodium      0
fiber       0
carbo       1
sugars      1
potass      2
vitamins    0
shelf       0
weight      0
cups        0
rating      0
dtype: int64

Drop ve Fill yöntemlerinini ikisini de kullanalım:
- carbohydrate ve sugar sütunlarında bulunan eksik değerleri silelim.
- potassium sütununda bulunan eksik değerleri median ile dolduralım.

In [25]:
df.shape

(77, 15)

In [26]:
df.dropna(subset=['carbo','sugars']).head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.0,0.75,34.384843

In [27]:
df.dropna(subset=['carbo','sugars']).shape

(76, 15)

In [28]:
df.shape  #oops! Görüldüğü üzere shape eski haline dönmüş. Çünkü biz bu işlemi kalıcı yapmadık.

(77, 15)

 `inplace=True` ile yapılan işlemi kalıcı kılabiliriz.

In [29]:
df.dropna(subset=['carbo', 'sugars'], inplace=True)

In [30]:
df.shape

(76, 15)

In [31]:
potass_median = df.potass.median()

potass_median

90.0

In [32]:
df.potass.fillna(potass_median, inplace=True)

In [33]:
df.head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,90.0,25,3,1.0,0.75,34.384843

## Applying Functions to Data - Fonksiyon

Her bir tahılın vitamin içeriği hakkındaki mevcut verilerimiz sadece üç farklı değer içermektedir.

In [34]:
df.vitamins.value_counts()

25     63
0       7
100     6
Name: vitamins, dtype: int64

Her tahılın en az 25 vitamin seviyesi içerip içermediğini bize bildirmek için veri çerçevesinde yeni bir sütun oluşturalım.

In [35]:
df['vitamin_at_least_25'] = df.vitamins >= 25

In [36]:
df.head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,vitamin_at_least_25
name,,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973,True
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679,False
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505,True
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912,True
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,90.0,25,3,1.0,0.75,34.384843,True

### .apply()

Her tahılı "düşük", "orta" veya "yüksek" vitamin düzeyine sahip olarak sınıflandırmak istersek ne olur? Pekala, eğer elimizde sadece bir değer varsa, bunu yapacak bir fonksiyon yaratmak oldukça kolay olurdu.

In [37]:
def get_vitamin_level(vitamins):
    if vitamins > 99:
        return 'high'
    elif vitamins > 24:
        return 'medium'
    else:
        return 'low'

In [38]:
get_vitamin_level(100)

'high'

In [39]:
get_vitamin_level(25)

'medium'

Şimdi bu işlevi vitamin sütunundaki her değere uygulamak için `.apply()` kullanacağız.

In [40]:
df.vitamins.apply(get_vitamin_level)    # bütün değerlere bu fonksiyonu uygula demek oluyor.

name
100% Bran                    medium
100% Natural Bran               low
All-Bran                     medium
All-Bran with Extra Fiber    medium
Almond Delight               medium
                              ...
Triples                      medium
Trix                         medium
Wheat Chex                   medium
Wheaties                     medium
Wheaties Honey Gold          medium
Name: vitamins, Length: 76, dtype: object

In [41]:
df['vitamin_level'] = df.vitamins.apply(get_vitamin_level)

In [42]:
df.head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,vitamin_at_least_25,vitamin_level
name,,,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973,True,medium
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679,False,low
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505,True,medium
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912,True,medium
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,90.0,25,3,1.0,0.75,34.384843,True,medium

Ayrıca lambda fonksiyonlarını da kullanabilirsiniz.`.apply()`

In [43]:
df['vitamin_perc'] = df.vitamins.apply(lambda x: str(x)+'%') #gelen değerin yanına '%' bunu ekle ve yaz

In [44]:
df.head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,vitamin_at_least_25,vitamin_level,vitamin_perc
name,,,,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973,True,medium,25%
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679,False,low,0%
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505,True,medium,25%
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912,True,medium,25%
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,90.0,25,3,1.0,0.75,34.384843,True,medium,25%

### .map()

Diyelim ki şu anda kodlanmış üretici sütununu üreticilerin gerçek adlarına dönüştürmek istiyoruz ve bize yardımcı olacak bu sözlüğümüz var.

In [45]:
mfr_dict = {
    'A': 'Am Home Food Prods',
    'G': 'General Mills',
    'K': 'Kelloggs',
    'N': 'Nabisco',
    'P': 'Post',
    'Q': 'Quaker Oats',
    'R': 'Ralston Purina'
}

Tek yapmamız gereken bu sözlüğü mevcut üretici sütunumuzla eşleştirmek.

In [46]:
df.mfr.map(mfr_dict)       # map şunu yapıyor; mfr deki her birini yap

name
100% Bran                           Nabisco
100% Natural Bran               Quaker Oats
All-Bran                           Kelloggs
All-Bran with Extra Fiber          Kelloggs
Almond Delight               Ralston Purina
                                  ...
Triples                       General Mills
Trix                          General Mills
Wheat Chex                   Ralston Purina
Wheaties                      General Mills
Wheaties Honey Gold           General Mills
Name: mfr, Length: 76, dtype: object

In [47]:
df['manufacturer'] = df.mfr.map(mfr_dict)

In [48]:
df.head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,vitamin_at_least_25,vitamin_level,vitamin_perc,manufacturer
name,,,,,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973,True,medium,25%,Nabisco
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679,False,low,0%,Quaker Oats
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505,True,medium,25%,Kelloggs
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912,True,medium,25%,Kelloggs
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,90.0,25,3,1.0,0.75,34.384843,True,medium,25%,Ralston Purina

`.apply()`, `.map()`, ve `.applymap()` arasındaki farklar çok küçük olabilir. Daha fazlası için bu [referansa](https://www.geeksforgeeks.org/difference-between-map-applymap-and-apply-methods-in-pandas/) göz atın.

## Grouping and Aggregating Data - Verileri Gruplama ve Toplama

Son olarak, pandas içindeki verileri gruplandırma kavramına bakalım.

Her üretici için tahıl porsiyonu başına ortalama kalori nedir?

In [49]:
df.groupby('manufacturer').calories.median()

manufacturer
Am Home Food Prods    100
General Mills         110
Kelloggs              110
Nabisco                90
Post                  110
Quaker Oats           100
Ralston Purina        110
Name: calories, dtype: int64

In [50]:
df.groupby('manufacturer').calories.median().sort_values(ascending=False)

manufacturer
Ralston Purina        110
Post                  110
Kelloggs              110
General Mills         110
Quaker Oats           100
Am Home Food Prods    100
Nabisco                90
Name: calories, dtype: int64

`.groupby()` öğesine bir sütun listesi ileterek birden çok özniteliğe göre gruplandırabiliriz.

In [51]:
df.groupby(['manufacturer', 'type'])[['calories']].median()

                         calories
manufacturer       type
Am Home Food Prods H          100
General Mills      C          110
Kelloggs           C          110
Nabisco            C           90
                   H          100
Post               C          110
Quaker Oats        C          100
Ralston Purina     C          110

Birden çok sütuna göre gruplama, çok düzeyli bir indeksle sonuçlanır. Bunların sütun olmasını tercih edersek, indeksi sıfırlayabiliriz.

In [52]:
df.groupby(['manufacturer', 'type'])[['calories']].median().reset_index()  # başına 0'dan başlayarak index koyar.

         manufacturer type  calories
0  Am Home Food Prods    H       100
1       General Mills    C       110
2            Kelloggs    C       110
3             Nabisco    C        90
4             Nabisco    H       100
5                Post    C       110
6         Quaker Oats    C       100
7      Ralston Purina    C       110

Birden çok sütunda toplama gerçekleştirebiliriz.

In [53]:
df.groupby('manufacturer')[['calories', 'sugars']].median()

                    calories  sugars
manufacturer
Am Home Food Prods       100     3.0
General Mills            110     8.5
Kelloggs                 110     7.0
Nabisco                   90     0.0
Post                     110    10.0
Quaker Oats              100     6.0
Ralston Purina           110     5.5

`.agg()` kullanarak ve bir toplama listesi ileterek aynı anda birden çok toplama yapabilirsiniz.

In [54]:
df.groupby('manufacturer').calories.agg(['mean', 'std', 'median', 'count'])  # agg() ile birden fazla hesaplama yaptırır.

                          mean        std  median  count
manufacturer
Am Home Food Prods  100.000000        NaN     100      1
General Mills       111.363636  10.371873     110     22
Kelloggs            108.695652  22.218818     110     23
Nabisco              86.666667  10.327956      90      6
Post                108.888889  10.540926     110      9
Quaker Oats          94.285714  31.547394     100      7
Ralston Purina      115.000000  22.677868     110      8

sütunlara farklı toplama işlevleri uygulamak için  `.agg()` öğesine bir sözlük iletin.

In [55]:
(df.groupby('manufacturer')[['mfr','calories', 'sugars', 'rating']].agg({ 'mfr': 'count','calories': 'median', 'sugars': 'mean','rating': 'mean' }))

                    mfr  calories    sugars     rating
manufacturer
Am Home Food Prods    1       100  3.000000  54.850917
General Mills        22       110  7.954545  34.485852
Kelloggs             23       110  7.565217  44.038462
Nabisco               6        90  1.833333  67.968567
Post                  9       110  8.777778  41.705744
Quaker Oats           7       100  6.142857  41.785647
Ralston Purina        8       110  6.125000  41.542997